"use strict";

(function(){
  const state={proposals:[]};
  const q=(s)=>document.querySelector(s);
  const esc=(v)=>String(v??"").replace(/[&<>"']/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
  function config(){return {base:(localStorage.getItem('openrabbit.apiBase')||'http://127.0.0.1:8787').replace(/\/$/,''),org:localStorage.getItem('openrabbit.orgId')||q('#orgId')?.value||'default',token:localStorage.getItem('openrabbit.token')||q('#token')?.value||''};}
  async function request(path,options={}){const c=config();const res=await fetch(`${c.base}/v1/orgs/${encodeURIComponent(c.org)}${path}`,{...options,headers:{'Content-Type':'application/json',...(c.token?{Authorization:`Bearer ${c.token}`}:{})}});const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body?.error?.message||`Request failed (${res.status})`);return body.data;}
  function card(p){const e=p.event||{};const evidence=(p.evidence||[]).join(' · ');return `<div class="activity-row meeting-proposal" data-proposal-id="${esc(p.id)}"><div class="row-top"><span class="row-title">${esc(e.title)}</span><span class="pill ${p.status==='proposed'?'proposed':p.status==='approved'||p.status==='executed'?'approved':''}">${esc(p.status)}</span></div><div class="row-meta">${esc(e.start)} → ${esc(e.end)}${e.location?` · ${esc(e.location)}`:''}</div><div class="row-meta">Source: ${esc(p.source?.subject||p.source?.messageId||'mail')} · confidence ${p.confidence==null?'—':Math.round(p.confidence*100)+'%'}</div>${evidence?`<div class="row-meta">Evidence: ${esc(evidence)}</div>`:''}<div class="actions">${p.status==='proposed'?`<button class="secondary proposal-edit">Edit</button><button class="dark proposal-approve">Approve</button><button class="danger proposal-reject">Reject</button>`:''}${p.status==='approved'?`<button class="dark proposal-execute">Add to calendar</button>`:''}${p.status==='executed'?`<span class="pill approved">Calendar event ${esc(p.calendarEventId||'created')}</span>`:''}</div></div>`;}
  function render(){const agent=q('#proposalQueue');if(agent)agent.innerHTML=state.proposals.length?state.proposals.map(card).join(''):'<div class="empty">No meeting proposals.</div>';const cal=q('#proposalCalendar');if(cal)cal.innerHTML=state.proposals.filter(p=>p.status!=='rejected').map(p=>`<div class="cal-item ${p.status==='proposed'?'proposed':p.status==='approved'||p.status==='executed'?'approved':''}" data-proposal-id="${esc(p.id)}"><strong>${esc(p.event.title)}</strong><br>${esc(p.event.start)} · ${esc(p.status)}</div>`).join('')||'<div class="empty">No proposed meetings.</div>';const count=state.proposals.filter(p=>p.status==='proposed').length;document.querySelectorAll('[data-proposal-count]').forEach(el=>el.textContent=String(count));}
  async function refresh(){state.proposals=await request('/meeting-proposals');render();}
  async function act(id,action,body){await request(`/meeting-proposals/${encodeURIComponent(id)}/${action}`,{method:'POST',body:JSON.stringify(body||{})});await refresh();}
  async function edit(id){const p=state.proposals.find(x=>x.id===id);if(!p)return;const title=prompt('Meeting title',p.event.title);if(title===null)return;const start=prompt('Start (ISO date/time)',p.event.start);if(start===null)return;const end=prompt('End (ISO date/time)',p.event.end);if(end===null)return;await request(`/meeting-proposals/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({event:{title,start,end}})});await refresh();}
  document.addEventListener('click',async(ev)=>{const row=ev.target.closest('[data-proposal-id]');if(!row)return;const id=row.dataset.proposalId;try{if(ev.target.closest('.proposal-approve'))await act(id,'approve');else if(ev.target.closest('.proposal-reject'))await act(id,'reject');else if(ev.target.closest('.proposal-execute'))await act(id,'execute');else if(ev.target.closest('.proposal-edit'))await edit(id);}catch(err){alert(err.message);}});
  q('#scanMeetingMail')?.addEventListener('click',async()=>{try{await request('/meeting-proposals/scan',{method:'POST',body:JSON.stringify({query:'is:unread',limit:25})});await refresh();}catch(err){alert(err.message);}});
  window.OpenRabbitProductivity={refresh,request,state};
  document.addEventListener('DOMContentLoaded',()=>refresh().catch(()=>render()));
})();
