"use strict";
const crypto=require('crypto');
const fs=require('fs');
const path=require('path');

const dataDir=process.env.OPENRABBIT_GATEWAY_DATA_DIR||path.join(process.cwd(),'.openrabbit-gateway');
const file=path.join(dataDir,'microsoft-tokens.enc.json');
const encSecret=String(process.env.OPENRABBIT_TOKEN_ENCRYPTION_KEY||'').trim();
const publicBaseUrl=String(process.env.OPENRABBIT_CONNECTION_GATEWAY_PUBLIC_URL||'http://127.0.0.1:8790').replace(/\/$/,'');
const states=new Map();
function configured(){return Boolean(process.env.MICROSOFT_CLIENT_ID&&process.env.MICROSOFT_CLIENT_SECRET);}
function key(){if(!encSecret)throw new Error('OPENRABBIT_TOKEN_ENCRYPTION_KEY is required');return crypto.createHash('sha256').update(encSecret).digest();}
function enc(obj){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',key(),iv),d=Buffer.concat([c.update(Buffer.from(JSON.stringify(obj))),c.final()]);return{iv:iv.toString('base64'),tag:c.getAuthTag().toString('base64'),data:d.toString('base64')};}
function dec(blob){const d=crypto.createDecipheriv('aes-256-gcm',key(),Buffer.from(blob.iv,'base64'));d.setAuthTag(Buffer.from(blob.tag,'base64'));return JSON.parse(Buffer.concat([d.update(Buffer.from(blob.data,'base64')),d.final()]).toString());}
function read(){try{return fs.existsSync(file)?dec(JSON.parse(fs.readFileSync(file,'utf8'))):{};}catch{return{};}}
function write(s){fs.mkdirSync(dataDir,{recursive:true});const t=file+'.tmp';fs.writeFileSync(t,JSON.stringify(enc(s)),{mode:0o600});fs.renameSync(t,file);}
function get(uid){return read()[uid]||null;}
function save(uid,t){const s=read();s[uid]={...t,updated_at:new Date().toISOString()};write(s);}
function remove(uid){const s=read();delete s[uid];write(s);}
async function fetchJson(url,opt={}){const r=await fetch(url,opt),text=await r.text();let b={};try{b=text?JSON.parse(text):{};}catch{b={message:text};}if(!r.ok)throw new Error(b?.error_description||b?.error?.message||b?.message||`Microsoft request failed (${r.status})`);return b;}
async function liveToken(uid){let t=get(uid);if(!t)return null;if(t.access_token&&Number(t.expires_at||0)>Date.now()+60000)return t;if(!t.refresh_token)return t;const tenant=process.env.MICROSOFT_TENANT||'common';const n=await fetchJson(`https://login.microsoftonline.com/${tenant}/oauth2/v2.0/token`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:process.env.MICROSOFT_CLIENT_ID,client_secret:process.env.MICROSOFT_CLIENT_SECRET,grant_type:'refresh_token',refresh_token:t.refresh_token,scope:process.env.MICROSOFT_OAUTH_SCOPES||'openid profile email offline_access User.Read Mail.Read Calendars.Read'})});t={...t,...n,refresh_token:n.refresh_token||t.refresh_token,expires_at:Date.now()+Number(n.expires_in||3600)*1000};save(uid,t);return t;}
function start(uid){if(!configured())throw new Error('Microsoft 365 sign-in is not available yet.');const state=crypto.randomBytes(24).toString('hex');states.set(state,{uid,created:Date.now()});const tenant=process.env.MICROSOFT_TENANT||'common';const u=new URL(`https://login.microsoftonline.com/${tenant}/oauth2/v2.0/authorize`);u.searchParams.set('client_id',process.env.MICROSOFT_CLIENT_ID);u.searchParams.set('response_type','code');u.searchParams.set('redirect_uri',`${publicBaseUrl}/oauth/microsoft/callback`);u.searchParams.set('response_mode','query');u.searchParams.set('scope',process.env.MICROSOFT_OAUTH_SCOPES||'openid profile email offline_access User.Read Mail.Read Calendars.Read');u.searchParams.set('state',state);return u.toString();}
function pop(state){const r=states.get(state);states.delete(state);if(!r||Date.now()-r.created>10*60*1000)return null;return r;}
async function exchange(code,record){const tenant=process.env.MICROSOFT_TENANT||'common';const t=await fetchJson(`https://login.microsoftonline.com/${tenant}/oauth2/v2.0/token`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:process.env.MICROSOFT_CLIENT_ID,client_secret:process.env.MICROSOFT_CLIENT_SECRET,grant_type:'authorization_code',code,redirect_uri:`${publicBaseUrl}/oauth/microsoft/callback`,scope:process.env.MICROSOFT_OAUTH_SCOPES||'openid profile email offline_access User.Read Mail.Read Calendars.Read'})});save(record.uid,{...t,expires_at:Date.now()+Number(t.expires_in||3600)*1000});}
async function verify(uid){if(!configured())return{connected:false,available:false,verified:false};try{const t=await liveToken(uid);if(!t)return{connected:false,available:true,verified:false};const me=await fetchJson('https://graph.microsoft.com/v1.0/me?$select=id,displayName,mail,userPrincipalName',{headers:{authorization:`Bearer ${t.access_token}`}});return{connected:true,available:true,verified:true,profile:{id:me.id,name:me.displayName,email:me.mail||me.userPrincipalName||''},updatedAt:t.updated_at||null};}catch(e){return{connected:false,available:true,verified:false,needsReconnect:true,message:e.message};}}
async function snapshot(uid){const t=await liveToken(uid);if(!t)return{connected:false,mail:[],calendar:[]};const h={authorization:`Bearer ${t.access_token}`};const now=new Date(),end=new Date(now.getTime()+30*864e5);const [mail,cal,me]=await Promise.all([fetchJson('https://graph.microsoft.com/v1.0/me/messages?$top=12&$select=id,subject,from,receivedDateTime,bodyPreview,isRead&$orderby=receivedDateTime%20desc',{headers:h}),fetchJson(`https://graph.microsoft.com/v1.0/me/calendarView?startDateTime=${encodeURIComponent(now.toISOString())}&endDateTime=${encodeURIComponent(end.toISOString())}&$top=20&$select=id,subject,start,end,location,onlineMeeting,isOnlineMeeting&$orderby=start/dateTime`,{headers:{...h,Prefer:'outlook.timezone="UTC"'}}),fetchJson('https://graph.microsoft.com/v1.0/me?$select=id,displayName,mail,userPrincipalName',{headers:h})]);return{connected:true,profile:{id:me.id,name:me.displayName,email:me.mail||me.userPrincipalName||''},mail:(mail.value||[]).map(m=>({id:m.id,subject:m.subject||'(No subject)',from:m.from?.emailAddress?.name||m.from?.emailAddress?.address||'',date:m.receivedDateTime,snippet:m.bodyPreview||'',unread:!m.isRead})),calendar:(cal.value||[]).map(e=>({id:e.id,title:e.subject||'(Untitled)',start:e.start?.dateTime||null,end:e.end?.dateTime||null,location:e.location?.displayName||'',meet:e.onlineMeeting?.joinUrl||''}))};}
module.exports={configured,start,pop,exchange,verify,snapshot,remove};
