"use strict";
const http=require('http'),crypto=require('crypto'),fs=require('fs'),path=require('path');
const port=Number(process.env.OPENRABBIT_CONNECTION_GATEWAY_PORT||8790),host=process.env.OPENRABBIT_CONNECTION_GATEWAY_HOST||'0.0.0.0';
const publicBaseUrl=String(process.env.OPENRABBIT_CONNECTION_GATEWAY_PUBLIC_URL||`http://127.0.0.1:${port}`).replace(/\/$/,''),dataDir=process.env.OPENRABBIT_GATEWAY_DATA_DIR||path.join(process.cwd(),'.openrabbit-gateway'),tokenFile=path.join(dataDir,'tokens.enc.json');
const appToken=String(process.env.OPENRABBIT_GATEWAY_APP_TOKEN||''),encSecret=String(process.env.OPENRABBIT_TOKEN_ENCRYPTION_KEY||''),supabaseUrl=String(process.env.SUPABASE_URL||'https://djplmhglilcwqfotnjew.supabase.co').replace(/\/$/,''),supabaseKey=String(process.env.SUPABASE_PUBLISHABLE_KEY||'sb_publishable_ZdtVEN0fzdTEQyfQRLfhDA_zjKarn2n');
const states=new Map();
const providers=[{id:'gmail',label:'Gmail',category:'mail',oauth:true},{id:'google-calendar',label:'Google Calendar',category:'calendar',oauth:true},{id:'hubspot',label:'HubSpot',category:'crm',oauth:true},{id:'meta',label:'Instagram / Facebook',category:'social',oauth:true},{id:'linkedin',label:'LinkedIn',category:'social',oauth:true},{id:'tiktok',label:'TikTok',category:'social',oauth:true},{id:'microsoft',label:'Microsoft 365',category:'mail-calendar',oauth:true,planned:true},{id:'google-maps',label:'Google Maps',category:'maps',oauth:false,platformCapability:true}];
function json(res,s,b){const p=JSON.stringify(b);res.writeHead(s,{'content-type':'application/json','cache-control':'no-store','access-control-allow-origin':process.env.OPENRABBIT_GATEWAY_CORS_ORIGIN||'*','access-control-allow-headers':'authorization,content-type,x-openrabbit-user','access-control-allow-methods':'GET,POST,DELETE,OPTIONS'});res.end(p)}
function html(res,s,b){res.writeHead(s,{'content-type':'text/html; charset=utf-8','cache-control':'no-store'});res.end(b)} function safe(v){return String(v||'').replace(/[<>&"']/g,'')}
function key(){if(!encSecret)throw Error('OPENRABBIT_TOKEN_ENCRYPTION_KEY is required');return crypto.createHash('sha256').update(encSecret).digest()}
function readStore(){try{if(!fs.existsSync(tokenFile))return{};const b=JSON.parse(fs.readFileSync(tokenFile,'utf8')),d=crypto.createDecipheriv('aes-256-gcm',key(),Buffer.from(b.iv,'base64'));d.setAuthTag(Buffer.from(b.tag,'base64'));return JSON.parse(Buffer.concat([d.update(Buffer.from(b.data,'base64')),d.final()]).toString())}catch(e){console.error('token read',e.message);return{}}}
function writeStore(o){fs.mkdirSync(dataDir,{recursive:true});const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',key(),iv),data=Buffer.concat([c.update(Buffer.from(JSON.stringify(o))),c.final()]);fs.writeFileSync(tokenFile,JSON.stringify({v:1,iv:iv.toString('base64'),tag:c.getAuthTag().toString('base64'),data:data.toString('base64')}),{mode:0o600})}
function getUserToken(u,id){return readStore()[u]?.[id]||null} function saveToken(u,id,t){const s=readStore();s[u]=s[u]||{};s[u][id]={...t,updated_at:new Date().toISOString()};writeStore(s)} function deleteToken(u,id){const s=readStore();if(s[u])delete s[u][id];writeStore(s)}
async function authenticate(req){const raw=String(req.headers.authorization||''),token=raw.startsWith('Bearer ')?raw.slice(7):'';if(token){try{const r=await fetch(`${supabaseUrl}/auth/v1/user`,{headers:{apikey:supabaseKey,authorization:`Bearer ${token}`}});if(r.ok){const u=await r.json();if(u?.id)return{mode:'user',userId:String(u.id),email:u.email||''}}}catch{}}if(appToken&&token&&Buffer.byteLength(appToken)===Buffer.byteLength(token)&&crypto.timingSafeEqual(Buffer.from(appToken),Buffer.from(token)))return{mode:'service',userId:String(req.headers['x-openrabbit-user']||'service').replace(/[^a-zA-Z0-9._@-]/g,'').slice(0,160)};return null}
function configured(id){if(['gmail','google-calendar'].includes(id))return!!(process.env.GOOGLE_OAUTH_CLIENT_ID&&process.env.GOOGLE_OAUTH_CLIENT_SECRET);if(id==='hubspot')return!!(process.env.HUBSPOT_OAUTH_CLIENT_ID&&process.env.HUBSPOT_OAUTH_CLIENT_SECRET);if(id==='meta')return!!(process.env.META_APP_ID&&process.env.META_APP_SECRET);if(id==='linkedin')return!!(process.env.LINKEDIN_CLIENT_ID&&process.env.LINKEDIN_CLIENT_SECRET);if(id==='tiktok')return!!(process.env.TIKTOK_CLIENT_KEY&&process.env.TIKTOK_CLIENT_SECRET);if(id==='google-maps')return!!(process.env.GOOGLE_MAPS_BROWSER_KEY||process.env.OPENRABBIT_MAPS_BROWSER_KEY);return false}
async function fj(url,opt={}){const r=await fetch(url,opt),t=await r.text();let b={};try{b=t?JSON.parse(t):{}}catch{b={message:t}}if(!r.ok)throw Error(b?.error?.message||b?.message||b?.error_description||b?.error||`Provider error ${r.status}`);return b}
async function liveToken(u,id){let t=getUserToken(u,id);if(!t)return null;if(['gmail','google-calendar'].includes(id)&&t.refresh_token&&Number(t.expires_at||0)<Date.now()+60000){const n=await fj('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:process.env.GOOGLE_OAUTH_CLIENT_ID,client_secret:process.env.GOOGLE_OAUTH_CLIENT_SECRET,refresh_token:t.refresh_token,grant_type:'refresh_token'})});t={...t,...n,refresh_token:t.refresh_token,expires_at:Date.now()+Number(n.expires_in||3600)*1000};saveToken(u,id,t)}if(id==='hubspot'&&t.refresh_token&&Number(t.expires_at||0)<Date.now()+60000){const n=await fj('https://api.hubapi.com/oauth/v1/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',client_id:process.env.HUBSPOT_OAUTH_CLIENT_ID,client_secret:process.env.HUBSPOT_OAUTH_CLIENT_SECRET,refresh_token:t.refresh_token})});t={...t,...n,refresh_token:n.refresh_token||t.refresh_token,expires_at:Date.now()+Number(n.expires_in||1800)*1000};saveToken(u,id,t)}return t}
async function verifyConnection(u,id){if(id==='google-maps')return{connected:false,available:configured(id),verified:configured(id)};const t=await liveToken(u,id);if(!t)return{connected:false,available:configured(id),verified:false};return{connected:true,available:true,verified:true,updatedAt:t.updated_at||null}}
async function connectionState(u){return Promise.all(providers.map(async p=>({...p,configured:configured(p.id),...(await verifyConnection(u,p.id))}))}
function state(u,id){const s=crypto.randomBytes(24).toString('hex');states.set(s,{u,id,at:Date.now()});return s} function pop(s){const r=states.get(s);states.delete(s);return r&&Date.now()-r.at<600000?r:null}
function googleStart(u,kind){const id=kind==='calendar'?'google-calendar':'gmail',url=new URL('https://accounts.google.com/o/oauth2/v2/auth');if(!configured(id))throw Error('Google sign-in is not configured.');url.searchParams.set('client_id',process.env.GOOGLE_OAUTH_CLIENT_ID);url.searchParams.set('redirect_uri',`${publicBaseUrl}/oauth/google/callback`);url.searchParams.set('response_type','code');url.searchParams.set('scope',`openid email ${id==='gmail'?'https://www.googleapis.com/auth/gmail.modify https://www.googleapis.com/auth/gmail.send':'https://www.googleapis.com/auth/calendar.events'}`);url.searchParams.set('access_type','offline');url.searchParams.set('prompt','consent');url.searchParams.set('state',state(u,id));return url.toString()}
function hubspotStart(u){if(!configured('hubspot'))throw Error('HubSpot sign-in is not configured.');const z=new URL('https://app.hubspot.com/oauth/authorize');z.searchParams.set('client_id',process.env.HUBSPOT_OAUTH_CLIENT_ID);z.searchParams.set('redirect_uri',`${publicBaseUrl}/oauth/hubspot/callback`);z.searchParams.set('scope',(process.env.HUBSPOT_OAUTH_SCOPES||'crm.objects.contacts.read crm.objects.contacts.write crm.objects.companies.read crm.objects.companies.write crm.objects.deals.read crm.objects.deals.write').trim());z.searchParams.set('state',state(u,'hubspot'));return z.toString()}
async function exchangeGoogle(code,r){const t=await fj('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:process.env.GOOGLE_OAUTH_CLIENT_ID,client_secret:process.env.GOOGLE_OAUTH_CLIENT_SECRET,code,grant_type:'authorization_code',redirect_uri:`${publicBaseUrl}/oauth/google/callback`})});saveToken(r.u,r.id,{...t,expires_at:Date.now()+Number(t.expires_in||3600)*1000})}
async function exchangeHubspot(code,r){const t=await fj('https://api.hubapi.com/oauth/v1/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',client_id:process.env.HUBSPOT_OAUTH_CLIENT_ID,client_secret:process.env.HUBSPOT_OAUTH_CLIENT_SECRET,redirect_uri:`${publicBaseUrl}/oauth/hubspot/callback`,code})});saveToken(r.u,'hubspot',{...t,expires_at:Date.now()+Number(t.expires_in||1800)*1000})}
function hv(h,n){return h?.find(x=>String(x.name).toLowerCase()===n.toLowerCase())?.value||''}
async function gmailData(u){const t=await liveToken(u,'gmail');if(!t)return{connected:false,items:[]};const l=await fj('https://gmail.googleapis.com/gmail/v1/users/me/messages?maxResults=12&q='+encodeURIComponent('newer_than:14d'),{headers:{authorization:`Bearer ${t.access_token}`}}),items=await Promise.all((l.messages||[]).slice(0,12).map(async m=>{const x=await fj(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${m.id}?format=metadata&metadataHeaders=From&metadataHeaders=Subject&metadataHeaders=Date`,{headers:{authorization:`Bearer ${t.access_token}`}});return{id:x.id,threadId:x.threadId,from:hv(x.payload?.headers,'From'),subject:hv(x.payload?.headers,'Subject')||'(No subject)',date:hv(x.payload?.headers,'Date'),snippet:x.snippet||'',unread:(x.labelIds||[]).includes('UNREAD')}}));return{connected:true,total:Number(l.resultSizeEstimate||items.length),items}}
async function calendarData(u){const t=await liveToken(u,'google-calendar');if(!t)return{connected:false,events:[]};const d=await fj('https://www.googleapis.com/calendar/v3/calendars/primary/events?singleEvents=true&orderBy=startTime&maxResults=20&timeMin='+encodeURIComponent(new Date().toISOString()),{headers:{authorization:`Bearer ${t.access_token}`}});return{connected:true,timeZone:d.timeZone||'',events:(d.items||[]).map(e=>({id:e.id,title:e.summary||'(Untitled)',start:e.start?.dateTime||e.start?.date,end:e.end?.dateTime||e.end?.date,location:e.location||'',meet:e.hangoutLink||''}))}}
async function hubspotData(u){const t=await liveToken(u,'hubspot');if(!t)return{connected:false,contacts:[],deals:[]};const h={authorization:`Bearer ${t.access_token}`},[c,d]=await Promise.all([fj('https://api.hubapi.com/crm/v3/objects/contacts?limit=20&properties=firstname,lastname,email,phone,company,hs_lead_status,lastmodifieddate',{headers:h}),fj('https://api.hubapi.com/crm/v3/objects/deals?limit=20&properties=dealname,amount,dealstage,pipeline,closedate,hs_lastmodifieddate',{headers:h})]);return{connected:true,contacts:(c.results||[]).map(x=>({id:x.id,...x.properties})),deals:(d.results||[]).map(x=>({id:x.id,...x.properties}))}}
async function liveSnapshot(u){const a=await Promise.allSettled([gmailData(u),calendarData(u),hubspotData(u)]),p=i=>a[i].status==='fulfilled'?a[i].value:{connected:false,error:a[i].reason?.message};return{generatedAt:new Date().toISOString(),mail:p(0),calendar:p(1),crm:p(2),social:{meta:{connected:!!getUserToken(u,'meta')},linkedin:{connected:!!getUserToken(u,'linkedin')},tiktok:{connected:!!getUserToken(u,'tiktok')}}}}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,publicBaseUrl);if(req.method==='OPTIONS')return json(res,204,{});if(url.pathname.startsWith('/oauth/')&&req.method==='GET'){const r=pop(url.searchParams.get('state'));if(!r)return html(res,400,'Authorization expired');try{if(url.pathname==='/oauth/google/callback')await exchangeGoogle(url.searchParams.get('code'),r);else if(url.pathname==='/oauth/hubspot/callback')await exchangeHubspot(url.searchParams.get('code'),r);else return html(res,404,'Not found');return html(res,200,'<h1>OpenRabbit connected</h1><p>You can close this window.</p>')}catch(e){return html(res,500,`<h1>Connection failed</h1><p>${safe(e.message)}</p>`)}}const i=await authenticate(req);if(!i)return json(res,401,{error:'UNAUTHORIZED'});const u=i.userId;if(req.method==='GET'&&url.pathname==='/v1/connections')return json(res,200,{user:u,connections:await connectionState(u)});if(req.method==='GET'&&url.pathname==='/v1/live')return json(res,200,await liveSnapshot(u));if(req.method==='GET'&&url.pathname==='/v1/platform/maps')return json(res,200,{available:configured('google-maps'),browserKey:process.env.GOOGLE_MAPS_BROWSER_KEY||process.env.OPENRABBIT_MAPS_BROWSER_KEY||''});if(req.method==='POST'&&url.pathname==='/v1/connections/google/start')return json(res,200,{authorizationUrl:googleStart(u,url.searchParams.get('kind'))});if(req.method==='POST'&&url.pathname==='/v1/connections/hubspot/start')return json(res,200,{authorizationUrl:hubspotStart(u)});const v=url.pathname.match(/^\/v1\/connections\/([a-z0-9-]+)\/verify$/);if(v&&req.method==='POST')return json(res,200,{provider:v[1],...(await verifyConnection(u,v[1]))});const d=url.pathname.match(/^\/v1\/connections\/([a-z0-9-]+)$/);if(d&&req.method==='DELETE'){deleteToken(u,d[1]);return json(res,200,{connected:false})}return json(res,404,{error:'NOT_FOUND'})}catch(e){console.error(e);if(!res.headersSent)json(res,500,{error:'INTERNAL_ERROR',message:e.message})}});
module.exports={server,providers,connectionState,verifyConnection,authenticate,liveSnapshot,liveToken};
