const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const desktopDir = path.join(root, 'clients', 'desktop-shell');
const workspaceDir = path.join(root, 'clients', 'real-estate-workspace');
const desktopPackage = JSON.parse(fs.readFileSync(path.join(desktopDir, 'package.json'), 'utf8'));
const mainSource = fs.readFileSync(path.join(desktopDir, 'main.js'), 'utf8');
const preloadSource = fs.readFileSync(path.join(desktopDir, 'preload.js'), 'utf8');
const workspaceHtml = fs.readFileSync(path.join(workspaceDir, 'index.html'), 'utf8');
const shellSource = fs.readFileSync(path.join(workspaceDir, 'shell.js'), 'utf8');
const productivitySource = fs.readFileSync(path.join(workspaceDir, 'productivity-client.js'), 'utf8');
assert.strictEqual(desktopPackage.main, 'main.js');
for (const script of ['dist:mac','dist:win','dist:linux']) assert.ok(desktopPackage.scripts[script], `${script} packaging script is required`);
for (const file of ['index.html','app.js','shell.js','productivity-client.js']) assert.ok(fs.existsSync(path.join(workspaceDir,file)), `${file} must exist`);
for (const view of ['dashboard','calendar','mail','agent','properties','social']) {assert.match(workspaceHtml,new RegExp(`id=["']view-${view}["']`));assert.match(shellSource,new RegExp(view));}
for (const id of ['dealTitle','dealMeta','setupPanel','app','newDealBtn','loadExistingBtn','createDealBtn','orgId','dealId','token','proposalQueue','proposalCalendar','scanMeetingMail']) assert.match(workspaceHtml,new RegExp(`id=["']${id}["']`),`${id} must remain available`);
assert.match(workspaceHtml,/script src=["']\.\/productivity-client\.js["']/);
assert.match(productivitySource,/\/meeting-proposals/,'desktop must consume meeting proposal API');
for (const action of ['approve','reject','execute']) assert.match(productivitySource,new RegExp(`['\"]${action}['\"]`),`desktop must support ${action}`);
assert.match(productivitySource,/method:'PATCH'/,'desktop must support proposal edits');
assert.match(productivitySource,/scanMeetingMail/,'mail view must trigger meeting scan');
assert.match(shellSource,/openrabbit\.activeView/);
assert.match(shellSource,/metaKey\|\|event\.ctrlKey/);
const resources=desktopPackage.build&&desktopPackage.build.extraResources;assert.ok(Array.isArray(resources));assert.ok(resources.some(e=>e.from==='../real-estate-workspace'&&e.to==='workspace'));
assert.match(mainSource,/contextIsolation:\s*true/);assert.match(mainSource,/nodeIntegration:\s*false/);assert.match(mainSource,/sandbox:\s*true/);assert.match(mainSource,/shell\.openExternal/);assert.match(mainSource,/process\.resourcesPath/);assert.ok(preloadSource.length>0);
console.log('desktop-shell.test.js: OK');
