"use strict";
const assert=require('assert');const fs=require('fs');const os=require('os');const path=require('path');
const {GMAIL_READONLY,CALENDAR_EVENTS_READONLY,DEFAULT_SCOPES,buildGoogleAuthorizationUrl,exchangeGoogleAuthorizationCode,saveRefreshTokenFile,loadRefreshTokenFile}=require('../integrations/google/oauth-authorization-flow');
(async()=>{
assert.deepEqual(DEFAULT_SCOPES,[GMAIL_READONLY,CALENDAR_EVENTS_READONLY]);
const built=buildGoogleAuthorizationUrl({clientId:'client-id',redirectUri:'http://127.0.0.1:53682/oauth/google/callback',state:'state-1'});const url=new URL(built.url);const scopes=url.searchParams.get('scope').split(' ');assert.equal(url.searchParams.get('access_type'),'offline');assert.equal(url.searchParams.get('include_granted_scopes'),'true');assert.equal(url.searchParams.get('state'),'state-1');assert(scopes.includes('https://www.googleapis.com/auth/gmail.readonly'));assert(scopes.includes('https://www.googleapis.com/auth/calendar.events.readonly'));assert(!scopes.includes('https://www.googleapis.com/auth/gmail.send'));assert(!scopes.includes('https://www.googleapis.com/auth/gmail.modify'));assert(!scopes.includes('https://www.googleapis.com/auth/calendar.events'));
const custom=buildGoogleAuthorizationUrl({clientId:'client-id',redirectUri:'http://127.0.0.1:53682/oauth/google/callback',state:'state-2',scopes:['scope-a','scope-a','scope-b']});assert.equal(new URL(custom.url).searchParams.get('scope'),'scope-a scope-b');assert.throws(()=>buildGoogleAuthorizationUrl({clientId:'client-id',redirectUri:'http://127.0.0.1:53682/oauth/google/callback',state:'state-3',scopes:[]}),/at least one scope/);
let seen='';const tokens=await exchangeGoogleAuthorizationCode({clientId:'client-id',clientSecret:'secret',redirectUri:'http://127.0.0.1:53682/oauth/google/callback',code:'abc',fetchImpl:async(_u,o)=>{seen=o.body;return {ok:true,json:async()=>({access_token:'access',refresh_token:'refresh',expires_in:3600})};}});assert.equal(tokens.refreshToken,'refresh');assert.match(seen,/grant_type=authorization_code/);
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'or-oauth-'));const file=path.join(dir,'token.json');saveRefreshTokenFile(file,'refresh-secret');assert.equal(loadRefreshTokenFile(file),'refresh-secret');if(process.platform!=='win32')assert.equal(fs.statSync(file).mode&0o777,0o600);console.log('google-oauth-authorization-flow.test.js passed');})().catch(e=>{console.error(e);process.exit(1);});
