"use strict";
const drawer=document.getElementById("agentDrawer"),talkBtn=document.getElementById("talkBtn"),closeDrawer=document.getElementById("closeDrawer"),agentSearch=document.getElementById("agentSearch"),dashboard=document.querySelector(".dashboard");
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const fmtTime=v=>{if(!v)return"";const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})};
const fmtDate=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString([],{weekday:"short",month:"short",day:"numeric"})};
async function json(url,opts){const r=await fetch(url,opts);const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||`${r.status} ${r.statusText}`);return p}
function openAgent(prefill=""){drawer.classList.add("open");const t=drawer.querySelector("textarea");if(prefill)t.value=prefill;setTimeout(()=>t.focus(),100)}function closeAgent(){drawer.classList.remove("open")}
function focusWindow(s){const p=document.querySelector(s);if(!p)return;document.querySelectorAll(".panel.focused").forEach(x=>x.classList.remove("focused"));p.classList.add("focused");p.scrollIntoView({behavior:"smooth",block:"center"});setTimeout(()=>p.classList.remove("focused"),1800)}
function expandWindow(p){if(!p)return;const a=p.classList.contains("expanded");document.querySelectorAll(".panel.expanded").forEach(x=>x.classList.remove("expanded"));document.body.classList.toggle("window-open",!a);if(!a){p.classList.add("expanded");p.scrollTop=0}}
function installWindowControls(){document.querySelectorAll(".panel:not(.agent-hero)").forEach(p=>{const h=p.querySelector(":scope > .panel-head");if(!h||h.querySelector(".window-controls"))return;const c=document.createElement("div");c.className="window-controls";c.innerHTML='<button class="window-focus">◎</button><button class="window-expand">↗</button>';h.appendChild(c);c.querySelector(".window-focus").onclick=e=>{e.stopPropagation();const k=[...p.classList].find(x=>["email","calendar","market","activity","crm","social"].includes(x));if(k)focusWindow(`.${k}`)};c.querySelector(".window-expand").onclick=e=>{e.stopPropagation();expandWindow(p)}})}
function addToast(m){let s=document.querySelector(".toast-stack");if(!s){s=document.createElement("div");s.className="toast-stack";document.body.appendChild(s)}const t=document.createElement("div");t.className="toast";t.textContent=m;s.appendChild(t);requestAnimationFrame(()=>t.classList.add("show"));setTimeout(()=>{t.classList.remove("show");setTimeout(()=>t.remove(),250)},2400)}
const openMarket=()=>location.href="./market.html",openCommunications=()=>location.href="./communications.html",openSocial=()=>location.href="./social.html",openCalendar=()=>location.href="./calendar.html",openCRM=()=>location.href="./crm.html";
function connectCard(body,provider,label,href){body.className="connection-empty";body.innerHTML=`<h3>${esc(label)}</h3><p>This panel stays empty until ${esc(provider)} is authorized.</p><a class="connection-action" href="${esc(href)}">Connect ${esc(provider)}</a>`}
function renderEmail(data){const body=document.getElementById("emailBody"),status=document.getElementById("emailStatus");status.textContent=`Live · ${data.accountId||"Gmail"}`;body.className="";const items=(data.messages||[]).slice(0,5);body.innerHTML=`<div class="mail-list">${items.map(m=>`<article><b>${esc(m.from||"Unknown sender")}</b><span>${esc(fmtTime(m.date))}</span><strong>${esc(m.subject||"(no subject)")}</strong><p>${esc(m.snippet||"")}</p></article>`).join("")}</div><button class="wide ghost" id="openEmail">Open Email</button>${items.length?"":"<div class=\"connection-empty\"><p>No inbox messages returned.</p></div>"}`;document.getElementById("openEmail")?.addEventListener("click",openCommunications)}
function eventStart(e){return e.start?.dateTime||e.start?.date||""}function eventEnd(e){return e.end?.dateTime||e.end?.date||""}
function renderCalendar(data){const body=document.getElementById("calendarBody"),status=document.getElementById("calendarStatus"),events=(data.events||data.items||[]).slice(0,7);status.textContent=`Live · ${data.accountId||"Google"}`;body.className="";body.innerHTML=`<div class="live-calendar-list"><div class="live-calendar-date">${esc(fmtDate(new Date()))}</div>${events.map(e=>`<article><time>${esc(e.start?.dateTime?fmtTime(eventStart(e)):"All day")}</time><div><b>${esc(e.summary||"(untitled event)")}</b>${e.location?`<span>${esc(e.location)}</span>`:""}</div></article>`).join("")}${events.length?"":"<div class=\"connection-empty\"><p>No events returned in the current window.</p></div>"}</div><button class="wide ghost" id="openCalendar">Open Calendar</button>`;document.getElementById("openCalendar")?.addEventListener("click",openCalendar)}
function renderCRM(contacts,deals,statusData){const body=document.getElementById("crmBody"),status=document.getElementById("crmStatus");status.textContent=`Live · ${statusData.accountId||"HubSpot"}`;body.className="";const cs=(contacts.results||contacts.contacts||[]).slice(0,6),ds=(deals.results||deals.deals||[]).slice(0,6);body.innerHTML=`<div class="live-crm-grid"><section><h3>Contacts</h3>${cs.map(c=>{const p=c.properties||c;return`<article><b>${esc([p.firstname,p.lastname].filter(Boolean).join(" ")||p.email||c.id)}</b><span>${esc(p.email||p.phone||"")}</span></article>`}).join("")||"<p>No contacts returned.</p>"}</section><section><h3>Deals</h3>${ds.map(d=>{const p=d.properties||d;return`<article><b>${esc(p.dealname||d.name||d.id)}</b><span>${esc(p.dealstage||"")}${p.amount?` · ${esc(p.amount)}`:""}</span></article>`}).join("")||"<p>No deals returned.</p>"}</section></div><button class="wide ghost" id="openCRM">Open CRM</button>`;document.getElementById("openCRM")?.addEventListener("click",openCRM)}
function loadGoogleMaps(apiKey){return new Promise((resolve,reject)=>{if(window.google?.maps)return resolve(window.google.maps);window.__openrabbitDashboardMapsReady=()=>resolve(window.google.maps);const s=document.createElement("script");s.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(apiKey)}&callback=__openrabbitDashboardMapsReady&loading=async`;s.async=true;s.defer=true;s.onerror=()=>reject(new Error("Google Maps failed to load"));document.head.appendChild(s)})}
async function renderMarket(statusData){const body=document.getElementById("marketBody"),status=document.getElementById("marketStatus");if(!statusData.googleMaps?.configured){status.textContent="Not connected";connectCard(body,"Google Maps","Map not connected","./connections.html");return}status.textContent="Live map";body.className="";body.innerHTML='<div id="dashboardLiveMap" class="dashboard-live-map"></div><div class="truth-note">Google Maps is live. Listing, pricing, DOM, inventory and comp statistics stay blank until an authoritative market-data source is connected.</div><button class="wide ghost" id="openMarket">Open Market</button>';document.getElementById("openMarket")?.addEventListener("click",openMarket);try{const cfg=await json("/api/config/public"),maps=await loadGoogleMaps(cfg.googleMapsBrowserKey);new maps.Map(document.getElementById("dashboardLiveMap"),{center:{lat:33.4484,lng:-112.0740},zoom:10,mapTypeControl:false,streetViewControl:false,fullscreenControl:false})}catch(e){document.getElementById("dashboardLiveMap").innerHTML=`<div class="connection-empty"><p>${esc(e.message)}</p></div>`}}
async function renderActivity(){const body=document.getElementById("activityBody");try{const p=await json("/api/audit"),events=(p.events||[]).slice(0,6);if(!events.length)return;body.className="";body.innerHTML=`<ul class="live-activity">${events.map(e=>`<li><b>${esc(e.type||"activity")}</b><span>${esc([e.provider,e.summary,e.accountId].filter(Boolean).join(" · "))}</span><small>${esc(fmtTime(e.timestamp))}</small></li>`).join("")}</ul>`}catch{}}
function renderEnvironment(s){const list=document.getElementById("environmentStatus"),agent=document.getElementById("agentStatus"),summary=document.getElementById("agentSummary");const states=[['Gmail',s.gmail?.connected],['Calendar',s.calendar?.connected],['HubSpot',s.hubspot?.connected],['Google Maps',s.googleMaps?.configured],['OpenAI',s.openai?.configured],['Social',false]];list.innerHTML=states.map(([n,on])=>`<li><span class="connection-dot ${on?'on':'off'}"></span>${esc(n)} — ${on?'live':'not connected'}</li>`).join("");agent.textContent=s.openai?.configured?'● Live':'● Not connected';summary.textContent=s.openai?.configured?'Live agent ready. Context is limited to sources shown as connected.':'Connect OpenAI to activate the agent.'}
async function hydrateDashboard(){let s;try{s=await json("/api/integrations/status")}catch(e){document.getElementById("environmentStatus").innerHTML=`<li>Integration server unavailable: ${esc(e.message)}</li>`;return}renderEnvironment(s);
  const emailBody=document.getElementById("emailBody");if(s.gmail?.connected){try{renderEmail(await json("/api/integrations/gmail/inbox?limit=5"))}catch(e){emailBody.innerHTML=`<p>${esc(e.message)}</p>`}}else{document.getElementById("emailStatus").textContent=s.gmail?.configured?'Ready to connect':'Not configured';connectCard(emailBody,"Gmail","Email not connected","/api/integrations/gmail/connect?redirectTo=/index.html")}
  const calBody=document.getElementById("calendarBody");if(s.calendar?.connected){try{const now=new Date(),start=new Date(now);start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+1);renderCalendar(await json(`/api/integrations/calendar/events?timeMin=${encodeURIComponent(start.toISOString())}&timeMax=${encodeURIComponent(end.toISOString())}&limit=20`))}catch(e){calBody.innerHTML=`<p>${esc(e.message)}</p>`}}else{document.getElementById("calendarStatus").textContent=s.calendar?.configured?'Ready to authorize':'Not configured';connectCard(calBody,"Google Calendar","Calendar not connected","/api/integrations/calendar/connect?redirectTo=/index.html")}
  const crmBody=document.getElementById("crmBody");if(s.hubspot?.connected){try{const [contacts,deals]=await Promise.all([json("/api/integrations/hubspot/contacts?limit=12"),json("/api/integrations/hubspot/deals?limit=12")]);renderCRM(contacts,deals,s.hubspot)}catch(e){crmBody.innerHTML=`<p>${esc(e.message)}</p>`}}else{document.getElementById("crmStatus").textContent=s.hubspot?.configured?'Ready to connect':'Not configured';connectCard(crmBody,"HubSpot","CRM not connected","/api/integrations/hubspot/connect?redirectTo=/index.html")}
  await renderMarket(s);await renderActivity();
}
function installInteractions(){document.querySelectorAll(".agent-actions button").forEach(b=>b.onclick=()=>{const p={"Find Opportunities":"Using only live connected data, identify the best opportunities I should act on today. Clearly say when a required data source is unavailable.","Draft Messages":"Using only live connected email and CRM context, draft the highest-priority messages I need to send and queue them for approval.","Analyze Market":"Analyze only the live market data currently connected to OpenRabbit. Do not invent listing or market statistics.","Manage Follow Ups":"Review live CRM, email, and calendar data together and identify follow-ups that are due or at risk.","Create Content":"Create today's social post from live connected context. If no social platform is connected, prepare a draft only.","Optimize Schedule":"Review my live calendar and connected work context and propose an optimized schedule without changing fixed meetings."};openAgent(p[b.textContent.trim()]||b.textContent.trim())});document.getElementById("socialSetup")?.addEventListener("click",()=>location.href="./connections.html")}
async function runAgent(){const t=drawer.querySelector("textarea"),button=drawer.querySelector(".primary"),input=t.value.trim();if(!input)return t.focus();button.disabled=true;button.textContent="OpenRabbit is analyzing…";try{const status=await json("/api/integrations/status"),r=await json("/api/agent/run",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({input,context:{workspace:"command-center",integrationStatus:status,policy:"Use connected live sources only. Never treat placeholder or unavailable data as factual."}})});let out=drawer.querySelector(".live-agent-output");if(!out){out=document.createElement("div");out.className="live-agent-output";drawer.appendChild(out)}out.textContent=r.text||"No response";addToast(`Live OpenRabbit response · ${r.model||"OpenAI"}`)}catch(e){addToast(e.message)}finally{button.disabled=false;button.textContent="Run Request"}}
talkBtn?.addEventListener("click",()=>openAgent());closeDrawer?.addEventListener("click",closeAgent);agentSearch?.addEventListener("keydown",e=>{if(e.key==="Enter"){openAgent(e.currentTarget.value.trim());e.currentTarget.value=""}});drawer?.querySelector(".primary")?.addEventListener("click",runAgent);document.addEventListener("keydown",e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();agentSearch?.focus()}if(e.key==="Escape"){if(document.querySelector(".panel.expanded")){document.querySelectorAll(".panel.expanded").forEach(p=>p.classList.remove("expanded"));document.body.classList.remove("window-open")}else closeAgent()}});document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>{const l=b.textContent.trim();if(l==="Home")return dashboard?.scrollIntoView({behavior:"smooth",block:"start"});if(l==="Calendar")return openCalendar();if(l==="Market")return openMarket();if(l==="Email")return openCommunications();if(l==="Social")return openSocial();if(l==="CRM")return openCRM()});installWindowControls();installInteractions();hydrateDashboard();