"use strict";

const drawer = document.getElementById("agentDrawer");
const talkBtn = document.getElementById("talkBtn");
const closeDrawer = document.getElementById("closeDrawer");
const agentSearch = document.getElementById("agentSearch");
const dashboard = document.querySelector(".dashboard");
function openAgent(prefill=""){drawer.classList.add("open");const textarea=drawer.querySelector("textarea");if(prefill)textarea.value=prefill;setTimeout(()=>textarea.focus(),100)}
function closeAgent(){drawer.classList.remove("open")}
function focusWindow(selector){const panel=document.querySelector(selector);if(!panel)return;document.querySelectorAll(".panel.focused").forEach(p=>p.classList.remove("focused"));panel.classList.add("focused");panel.scrollIntoView({behavior:"smooth",block:"center"});setTimeout(()=>panel.classList.remove("focused"),1800)}
function expandWindow(panel){if(!panel)return;const already=panel.classList.contains("expanded");document.querySelectorAll(".panel.expanded").forEach(p=>p.classList.remove("expanded"));document.body.classList.toggle("window-open",!already);if(!already){panel.classList.add("expanded");panel.scrollTop=0}}
function installWindowControls(){document.querySelectorAll(".panel:not(.agent-hero)").forEach(panel=>{const head=panel.querySelector(":scope > .panel-head");if(!head||head.querySelector(".window-controls"))return;const controls=document.createElement("div");controls.className="window-controls";controls.innerHTML='<button class="window-focus" title="Focus window">◎</button><button class="window-expand" title="Expand window">↗</button>';head.appendChild(controls);controls.querySelector(".window-focus").onclick=e=>{e.stopPropagation();focusWindow(`.${[...panel.classList].find(x=>["email","calendar","market","activity","crm","social"].includes(x))}`)};controls.querySelector(".window-expand").onclick=e=>{e.stopPropagation();expandWindow(panel)}})}
function addToast(message){let stack=document.querySelector(".toast-stack");if(!stack){stack=document.createElement("div");stack.className="toast-stack";document.body.appendChild(stack)}const toast=document.createElement("div");toast.className="toast";toast.textContent=message;stack.appendChild(toast);requestAnimationFrame(()=>toast.classList.add("show"));setTimeout(()=>{toast.classList.remove("show");setTimeout(()=>toast.remove(),250)},2200)}
const openDeal=()=>window.location.href="./deal.html";const openMarket=()=>window.location.href="./market.html";const openCommunications=()=>window.location.href="./communications.html";const openSocial=()=>window.location.href="./social.html";
function installCardInteractions(){document.querySelectorAll(".mail-list article").forEach(item=>item.onclick=()=>{item.classList.toggle("selected");addToast(`Opened: ${item.querySelector("strong")?.textContent?.trim()||"Email"}`)});document.querySelector(".email .wide")?.addEventListener("click",openCommunications);document.querySelectorAll(".kanban article").forEach(card=>card.onclick=()=>{document.querySelectorAll(".kanban article.selected").forEach(x=>x.classList.remove("selected"));card.classList.add("selected");const name=card.querySelector("b")?.textContent?.trim()||"CRM record";if(name.includes("1638 W Mohave")){openDeal();return}openAgent(`Open the full record for ${name}, summarize the latest activity, and recommend the next action.`)});document.querySelectorAll(".event").forEach(eventCard=>eventCard.onclick=()=>{document.querySelectorAll(".event.selected").forEach(x=>x.classList.remove("selected"));eventCard.classList.add("selected");addToast(`Selected ${eventCard.querySelector("b")?.textContent?.trim()||"calendar event"}`)});document.querySelector(".property-card")?.addEventListener("click",openDeal);document.querySelectorAll(".map-actions button").forEach(button=>{if(["Find Deals","Run Comps","Market Trends"].includes(button.textContent.trim()))button.addEventListener("click",openMarket)});document.querySelectorAll(".social button").forEach(button=>{if(!button.closest(".window-controls"))button.addEventListener("click",openSocial)});document.querySelectorAll(".agent-actions button").forEach(button=>button.onclick=()=>{const prompts={"Find Opportunities":"Scan my market and pipeline for the best opportunities I should act on today.","Draft Messages":"Draft the highest-priority messages I need to send today and queue them for approval.","Analyze Market":"Analyze current Phoenix market conditions and surface anything that changes my strategy.","Manage Follow Ups":"Review CRM, email, and calendar together and identify every follow-up that is due or at risk.","Create Content":"Create today's social post based on my active deals, market activity, and content calendar.","Optimize Schedule":"Review my calendar, open tasks, follow-ups, and priorities and propose an optimized schedule."};openAgent(prompts[button.textContent.trim()]||button.textContent.trim())})}
function runAgentDemo(){const textarea=drawer.querySelector("textarea");if(!textarea.value.trim()){textarea.focus();return}addToast("OpenRabbit analyzed the environment and prepared a draft action plan.");textarea.value="";closeAgent()}
talkBtn?.addEventListener("click",()=>openAgent());closeDrawer?.addEventListener("click",closeAgent);agentSearch?.addEventListener("keydown",e=>{if(e.key==="Enter"){openAgent(e.currentTarget.value.trim());e.currentTarget.value=""}});drawer?.querySelector(".primary")?.addEventListener("click",runAgentDemo);document.addEventListener("keydown",e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();agentSearch?.focus()}if(e.key==="Escape"){if(document.querySelector(".panel.expanded")){document.querySelectorAll(".panel.expanded").forEach(p=>p.classList.remove("expanded"));document.body.classList.remove("window-open")}else closeAgent()}});document.querySelectorAll(".nav").forEach(button=>button.onclick=()=>{document.querySelectorAll(".nav").forEach(item=>item.classList.remove("active"));button.classList.add("active");const label=button.textContent.trim();if(label==="Home"){dashboard?.scrollIntoView({behavior:"smooth",block:"start"});return}if(label==="Market"){openMarket();return}if(label==="Email"){openCommunications();return}if(label==="Social"){openSocial();return}focusWindow({Calendar:".calendar",CRM:".crm"}[label])});document.querySelectorAll(".tabs, .segmented").forEach(group=>group.querySelectorAll("button").forEach(button=>button.onclick=()=>{group.querySelectorAll("button").forEach(item=>item.classList.remove("active"));button.classList.add("active")}));installWindowControls();installCardInteractions();