"use strict";
const drawer=document.getElementById("marketAgentDrawer"),closeDrawer=document.getElementById("marketCloseDrawer"),runAgent=document.getElementById("marketRunAgent"),textarea=drawer?.querySelector("textarea");
let selectedLocation=null;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function openAgent(prompt=""){drawer?.classList.add("open");if(textarea){textarea.value=prompt;setTimeout(()=>textarea.focus(),80)}}
function closeAgent(){drawer?.classList.remove("open")}
window.addEventListener("openrabbit:map-search",e=>{selectedLocation=e.detail||null;const selected=document.getElementById("selectedLocation"),intel=document.getElementById("propertyIntel");if(!selected)return;if(!selectedLocation){selected.textContent="Search an address or place on the map. The selected location will be attached to OpenRabbit automatically.";return}selected.innerHTML=`<b style="color:#dce8fa">${esc(selectedLocation.name||"Selected location")}</b><br>${esc(selectedLocation.address||"")}<br><small>${selectedLocation.lat?.toFixed?.(6)||""}, ${selectedLocation.lng?.toFixed?.(6)||""}</small><p><button id="analyzeSelected">Analyze with OpenRabbit</button></p>`;document.getElementById("analyzeSelected")?.addEventListener("click",()=>openAgent(`Analyze this selected location using only live connected context: ${selectedLocation.address||selectedLocation.name}. Tell me what you know, what you do not know, and what data source would be needed for pricing, listing status, comps, zoning, or investment analysis.`));if(intel)intel.innerHTML=`<b style="color:#dce8fa">${esc(selectedLocation.address||selectedLocation.name)}</b><p>Google Maps location selected. No listing, pricing, comp or market facts are inferred from the map alone.</p>`});
document.getElementById("marketAgentBtn")?.addEventListener("click",()=>openAgent("Review the live selected map context and connected OpenRabbit sources. Recommend useful next actions without inventing property or listing data."));
closeDrawer?.addEventListener("click",closeAgent);
runAgent?.addEventListener("click",async()=>{const input=textarea?.value.trim();if(!input)return textarea?.focus();runAgent.disabled=true;runAgent.textContent="OpenRabbit is analyzing…";try{const status=await fetch("/api/integrations/status").then(r=>r.json());const r=await fetch("/api/agent/run",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({input,context:{workspace:"market",selectedLocation,integrationStatus:status,policy:"Use only live connected context. Google Maps location data is not listing, valuation, comp, zoning or MLS data. Clearly identify missing sources."}})}),p=await r.json();if(!r.ok)throw new Error(p.error||"Agent failed");let out=drawer.querySelector(".live-agent-output");if(!out){out=document.createElement("div");out.className="live-agent-output";out.style.cssText="margin-top:14px;padding:12px;border:1px solid #29476b;border-radius:10px;color:#cdd9eb;white-space:pre-wrap;line-height:1.5;max-height:50vh;overflow:auto";drawer.appendChild(out)}out.textContent=p.text||"No response"}catch(e){alert(e.message)}finally{runAgent.disabled=false;runAgent.textContent="Run Request"}});
document.addEventListener("keydown",e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();openAgent()}if(e.key==="Escape")closeAgent()});