"use strict";

(()=>{
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const fmt=v=>{if(!v)return"Time needs confirmation";const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString([],{weekday:"short",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})};
  async function api(url,opts){const r=await fetch(url,opts);const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||`Request failed: ${r.status}`);return p}
  async function decide(id,action){const p=await api(`/api/proactive/meeting-proposals/${encodeURIComponent(id)}/${action}`,{method:"POST"});window.dispatchEvent(new CustomEvent("openrabbit:proposal-decided",{detail:p.proposal}));await refresh()}
  function card(p){return `<article class="proposal-card proposal-${esc(p.status)}" data-proposal-id="${esc(p.id)}"><div class="proposal-accent"></div><div class="proposal-copy"><small>MEETING IDENTIFIED · ${Math.round(Number(p.confidence||0)*100)}% confidence</small><b>${esc(p.title)}</b><span>${esc(fmt(p.start))}${p.location?` · ${esc(p.location)}`:""}</span><p>${esc(p.rationale||"")}</p><em>From: ${esc(p.sourceFrom||p.sourceSubject||"Gmail")}</em></div>${p.status==="pending"?`<div class="proposal-actions"><button data-proposal-action="approve">Approve</button><button data-proposal-action="reject">Deny</button></div>`:`<span class="proposal-state">${esc(p.status)}</span>`}</article>`}
  function installHandlers(root){root.querySelectorAll("[data-proposal-action]").forEach(b=>b.onclick=async e=>{e.stopPropagation();const c=b.closest("[data-proposal-id]");b.disabled=true;try{await decide(c.dataset.proposalId,b.dataset.proposalAction)}catch(err){alert(err.message)}finally{b.disabled=false}})}
  function renderHome(proposals){const body=document.getElementById("activityBody");if(!body)return;const pending=proposals.filter(p=>p.status==="pending");const wrap=document.createElement("div");wrap.id="proactiveMeetingQueue";wrap.className="proposal-queue";wrap.innerHTML=`<div class="proposal-queue-head"><b>${pending.length} meeting${pending.length===1?"":"s"} identified</b><button id="scanNow">Scan inbox now</button></div>${pending.map(card).join("")||'<p class="proposal-empty">No pending meeting proposals.</p>'}`;
    const old=document.getElementById("proactiveMeetingQueue");if(old)old.replaceWith(wrap);else body.prepend(wrap);installHandlers(wrap);wrap.querySelector("#scanNow")?.addEventListener("click",async()=>{const b=wrap.querySelector("#scanNow");b.disabled=true;b.textContent="Scanning…";try{await api("/api/proactive/scan",{method:"POST",headers:{"content-type":"application/json"},body:"{}"});await refresh()}catch(e){alert(e.message)}finally{b.disabled=false;b.textContent="Scan inbox now"}})}
  function eventTop(value){const d=new Date(value),mins=d.getHours()*60+d.getMinutes(),start=7*60;return Math.max(0,Math.round((mins-start)*.64))}
  function eventHeight(start,end){if(!start||!end)return 44;const mins=Math.max(30,(new Date(end)-new Date(start))/60000);return Math.min(110,Math.max(42,Math.round(mins*.64)))}
  function renderCalendar(proposals){const box=document.querySelector(".events");if(!box)return;box.querySelectorAll(".proposed-calendar-event").forEach(e=>e.remove());const today=new Date();for(const p of proposals.filter(p=>p.status==="pending"&&p.start)){const d=new Date(p.start);if(d.toDateString()!==today.toDateString())continue;const el=document.createElement("article");el.className="event proposed-calendar-event";el.style.cssText=`top:${eventTop(p.start)}px;height:${eventHeight(p.start,p.end)}px`;
      el.dataset.proposalId=p.id;el.innerHTML=`<small>PROPOSED · ${esc(fmt(p.start))}</small><b>${esc(p.title)}</b><span>${esc(p.sourceSubject||"Identified from Gmail")}</span><div class="proposal-inline-actions"><button data-proposal-action="approve">Approve</button><button data-proposal-action="reject">Deny</button></div>`;box.appendChild(el)}installHandlers(box)}
  async function refresh(){try{const p=await api("/api/proactive/meeting-proposals");const proposals=p.proposals||[];renderHome(proposals);renderCalendar(proposals)}catch(e){console.warn("Proactive queue unavailable",e)}}
  window.addEventListener("openrabbit:proposal-decided",()=>setTimeout(refresh,250));refresh();setInterval(refresh,30000);
})();